test-gateway:
  image: node:20
  stage: test
  script:
    - cd gateway
    - npm ci
    - npm run test
  artifacts:
    paths:
      - ./gateway/node_modules
    expire_in: 1h

build-gateway:
  image: node:20
  stage: build
  script:
    - cd gateway
    - npm run build
