stages:
  - test
  - build

test_gateway:
  image: node:20
  stage: test
  script:
    - cd gateway
    - npm ci
    - npm run test

build_gateway:
  image: node:20
  stage: build
  script:
    - cd gateway
    - npm ci
    - npm run build
